name: Custom Windows Client Generator
run-name: Custom Windows Client Generator
on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Rendezvous Server'
        required: true
        default: ''
        type: string
      key:
        description: 'Public Key'
        required: true
        default: ''
        type: string
      apiServer:
        description: 'API Server'
        required: true
        default: ''
        type: string
      custom:
        description: "Custom JSON"
        required: true
        default: ''
        type: string
      uuid:
        description: "UUID of request"
        required: true
        default: ''
        type: string
      iconlink:
        description: "Icon link"
        required: false
        default: 'false'
        type: string
      logolink:
        description: "Logo link"
        required: false
        default: 'false'
        type: string
      appname:
        description: "App name"
        required: true
        default: 'rustdesk'
        type: string
      filename:
        description: "Filename"
        required: true
        default: 'rustdesk'
        type: string
      extras:
        description: "Extra inputs in JSON"
        required: true
        default: '{}'
        type: string

env:
  SCITER_RUST_VERSION: "1.75"
  RUST_VERSION: "1.75"
  CARGO_NDK_VERSION: "3.1.2"
  FLUTTER_VERSION: "3.24.5"
  LLVM_VERSION: "15.0.6"
  SIGNING_ENABLED: ${{ secrets.SIGN_API_KEY != '' && secrets.SIGN_BASE_URL != '' }}
  STATUS_URL: ${{ fromJson(inputs.extras).rdgen == 'true' ? secrets.GENURL : inputs.apiServer }}/updategh

jobs:
  build:
    name: Build Custom Windows Client
    runs-on: windows-2022
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: rustdesk/rustdesk
          ref: refs/tags/${{ env.VERSION }}
          submodules: recursive

      - name: Restore bridge files
        uses: actions/download-artifact@v3
        with:
          name: bridge-artifact
          path: ./

      - name: Report Status (10% complete)
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ env.STATUS_URL }}
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"uuid": "${{ inputs.uuid }}", "status": "10% complete"}'

      - name: Apply custom patches
        run: |
          if ${{ fromJson(inputs.extras).rdgen == 'true' }}; then
            Invoke-WebRequest -Uri https://raw.githubusercontent.com/bryangerlach/rdgen/master/.github/patches/allowCustom.diff -OutFile allowCustom.diff
            git apply allowCustom.diff
          fi

      - name: Build application
        run: |
          python3 build.py --portable --hwcodec --flutter --vram --skip-portable-pack
          mv ./flutter/build/windows/x64/runner/Release ./rustdesk

      - name: Sign artifacts
        if: ${{ env.SIGNING_ENABLED }}
        run: |
          curl -X POST -F "file=@./rustdesk/unsigned_files.zip" \
            -H "X-API-KEY: ${{ secrets.SIGN_API_KEY }}" \
            -m 900 \
            "${{ secrets.SIGN_BASE_URL }}/sign/" -o ./rustdesk/signed_files.zip
          Expand-Archive -Path ./rustdesk/signed_files.zip -DestinationPath ./rustdesk/ -Force

      - name: Upload artifacts
        run: |
          curl -i -X POST -H "Content-Type: multipart/form-data" -H "Authorization: Bearer ${{ fromJson(inputs.extras).token }}" \
            -F "file=@./rustdesk/${{ inputs.filename }}.exe" -F "uuid=${{ inputs.uuid }}" \
            --max-time 600 --retry 10 ${{ secrets.GENURL }}/save_custom_client

      - name: Report Completion
        run: |
          echo "Build completed successfully!"
